apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: camel-wildfly-notification-configmap
data:
  application.properties: |-
    camel.mail.prefix: smtp
    camel.mail.host: localhost
    camel.mail.port: 2525
